@baseUrl = http://localhost:3001
# id here, again
@myUserId = c2c0f2fd-452d-4f68-a88f-d46a82e116cb


### ------------------------------------------------
### ดูประวัติทั้งหมดของผู้เล่น
### ------------------------------------------------
GET {{baseUrl}}/history/{{myUserId}}