@baseUrl = http://localhost:3001


### ------------------------------------------------
### 1. ทดสอบ Login ด้วยชื่อ "Ong" (สร้างใหม่ / ดึงข้อมูลเดิม)
### ------------------------------------------------
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "nickname": "Ong"
}


### ------------------------------------------------
### 2. ทดสอบ Login ด้วยชื่อผู้เล่นคนที่สอง
### ------------------------------------------------
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "nickname": "weerayosong"
}


### ------------------------------------------------
### 3. ทดสอบส่งชื่อว่างเปล่า (คาดหวังผลลัพธ์: 400 Bad Request)
### ------------------------------------------------
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "nickname": ""
}